/* AUTO-GENERATED by tools/generate_build.py. DO NOT EDIT. */
const VERSION = "1.7.4";
const SOURCE_SHA256 = "c78785f5db9945c68377ed0b8d680999ab64668f4c232b9ae48e94574fa3e873";
const CACHE_NAME = "diplocraft-shell-v1.7.4-20260618_1812";
const CACHE_PREFIX = "diplocraft-";
const PRECACHE_URLS = [
  "./404.html",
  "./assets/pwa/apple-touch-icon-180.png",
  "./assets/pwa/icon-128.png",
  "./assets/pwa/icon-192.png",
  "./assets/pwa/icon-256.png",
  "./assets/pwa/icon-384.png",
  "./assets/pwa/icon-512.png",
  "./assets/pwa/icon-64.png",
  "./assets/pwa/icon-96.png",
  "./assets/pwa/icon-maskable-512.png",
  "./assets/pwa/screenshot-desktop-1280x720.png",
  "./assets/pwa/screenshot-mobile-720x1280.png",
  "./assets/pwa/splash-1170x2532.png",
  "./assets/pwa/splash-1290x2796.png",
  "./assets/pwa/splash-1536x2048.png",
  "./assets/pwa/splash-2048x1536.png",
  "./assets/pwa/splash-750x1334.png",
  "./assets/runtime/backgrounds/bg_crisis_scene_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_crisis_scene_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_crisis_scene_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_crisis_scene_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_dashboard_city_view_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_dashboard_city_view_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_dashboard_city_view_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_dashboard_city_view_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_diplomacy_room_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_diplomacy_room_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_diplomacy_room_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_diplomacy_room_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_economy_financial_center_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_economy_financial_center_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_economy_financial_center_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_economy_financial_center_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_election_room_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_election_room_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_election_room_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_election_room_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_global_map_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_global_map_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_global_map_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_global_map_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_main_menu_presidential_office_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_main_menu_presidential_office_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_main_menu_presidential_office_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_main_menu_presidential_office_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_military_command_center_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_military_command_center_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_military_command_center_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_military_command_center_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_parliament_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_parliament_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_parliament_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_parliament_v1--mobile.webp",
  "./assets/runtime/backgrounds/bg_press_conference_stage_v1--desktop.avif",
  "./assets/runtime/backgrounds/bg_press_conference_stage_v1--desktop.webp",
  "./assets/runtime/backgrounds/bg_press_conference_stage_v1--mobile.avif",
  "./assets/runtime/backgrounds/bg_press_conference_stage_v1--mobile.webp",
  "./assets/runtime/cards/card_diplomacy_v1--card.avif",
  "./assets/runtime/cards/card_diplomacy_v1--card.webp",
  "./assets/runtime/cards/card_economy_v1--card.avif",
  "./assets/runtime/cards/card_economy_v1--card.webp",
  "./assets/runtime/cards/card_government_v1--card.avif",
  "./assets/runtime/cards/card_government_v1--card.webp",
  "./assets/runtime/cards/card_intelligence_v1--card.avif",
  "./assets/runtime/cards/card_intelligence_v1--card.webp",
  "./assets/runtime/cards/card_military_v1--card.avif",
  "./assets/runtime/cards/card_military_v1--card.webp",
  "./assets/runtime/cards/card_projects_v1--card.avif",
  "./assets/runtime/cards/card_projects_v1--card.webp",
  "./assets/runtime/characters/char_leader_latest_v1--display.avif",
  "./assets/runtime/characters/char_leader_latest_v1--display.webp",
  "./assets/runtime/characters/char_leader_latest_v1--thumb.avif",
  "./assets/runtime/characters/char_leader_latest_v1--thumb.webp",
  "./assets/runtime/characters/char_leader_male_black_v1--display.avif",
  "./assets/runtime/characters/char_leader_male_black_v1--display.webp",
  "./assets/runtime/characters/char_leader_male_black_v1--thumb.avif",
  "./assets/runtime/characters/char_leader_male_black_v1--thumb.webp",
  "./assets/runtime/characters/char_leader_male_elder_refined_v1--display.avif",
  "./assets/runtime/characters/char_leader_male_elder_refined_v1--display.webp",
  "./assets/runtime/characters/char_leader_male_elder_refined_v1--thumb.avif",
  "./assets/runtime/characters/char_leader_male_elder_refined_v1--thumb.webp",
  "./assets/runtime/characters/char_leader_male_elder_v1--display.avif",
  "./assets/runtime/characters/char_leader_male_elder_v1--display.webp",
  "./assets/runtime/characters/char_leader_male_elder_v1--thumb.avif",
  "./assets/runtime/characters/char_leader_male_elder_v1--thumb.webp",
  "./assets/runtime/characters/char_leader_male_white_v1--display.avif",
  "./assets/runtime/characters/char_leader_male_white_v1--display.webp",
  "./assets/runtime/characters/char_leader_male_white_v1--thumb.avif",
  "./assets/runtime/characters/char_leader_male_white_v1--thumb.webp",
  "./assets/runtime/icons/icon_set_v1--ui.avif",
  "./assets/runtime/icons/icon_set_v1--ui.webp",
  "./assets/runtime/parties/party_mdb_card_v1--party.avif",
  "./assets/runtime/parties/party_mdb_card_v1--party.webp",
  "./assets/runtime/parties/party_novo_card_v1--party.avif",
  "./assets/runtime/parties/party_novo_card_v1--party.webp",
  "./assets/runtime/parties/party_pl_card_v1--party.avif",
  "./assets/runtime/parties/party_pl_card_v1--party.webp",
  "./assets/runtime/parties/party_pp_card_v1--party.avif",
  "./assets/runtime/parties/party_pp_card_v1--party.webp",
  "./assets/runtime/parties/party_psb_card_v1--party.avif",
  "./assets/runtime/parties/party_psb_card_v1--party.webp",
  "./assets/runtime/parties/party_psd_card_v1--party.avif",
  "./assets/runtime/parties/party_psd_card_v1--party.webp",
  "./assets/runtime/parties/party_psdb_card_v1--party.avif",
  "./assets/runtime/parties/party_psdb_card_v1--party.webp",
  "./assets/runtime/parties/party_psol_card_v1--party.avif",
  "./assets/runtime/parties/party_psol_card_v1--party.webp",
  "./assets/runtime/parties/party_pt_card_v1--party.avif",
  "./assets/runtime/parties/party_pt_card_v1--party.webp",
  "./assets/runtime/parties/party_pv_card_v1--party.avif",
  "./assets/runtime/parties/party_pv_card_v1--party.webp",
  "./assets/runtime/parties/party_republicanos_card_v1--party.avif",
  "./assets/runtime/parties/party_republicanos_card_v1--party.webp",
  "./assets/runtime/parties/party_uniao_card_v1--party.avif",
  "./assets/runtime/parties/party_uniao_card_v1--party.webp",
  "./content/core/campaign-core.json",
  "./content/core/unlocks-core.json",
  "./content/manifest.json",
  "./favicon.svg",
  "./index.html",
  "./manifest.webmanifest",
  "./src/core/assets.js",
  "./src/core/build.js",
  "./src/core/desktop.js",
  "./src/core/dom.js",
  "./src/core/errorBoundary.js",
  "./src/core/fullscreen.js",
  "./src/core/i18n.js",
  "./src/core/mobile.js",
  "./src/core/pwa.js",
  "./src/core/resilience.js",
  "./src/core/router.js",
  "./src/core/saveManager.js",
  "./src/core/scrollExperience.js",
  "./src/core/stateFactory.js",
  "./src/core/storage.js",
  "./src/data/assetCatalog.js",
  "./src/data/avatars.js",
  "./src/data/budgetTaxData.js",
  "./src/data/cabinetAdministrationData.js",
  "./src/data/content.js",
  "./src/data/crisisData.js",
  "./src/data/diplomacyData.js",
  "./src/data/economyData.js",
  "./src/data/economyDeepData.js",
  "./src/data/electionData.js",
  "./src/data/governmentCreationData.js",
  "./src/data/governmentData.js",
  "./src/data/governmentInstitutionData.js",
  "./src/data/mediaData.js",
  "./src/data/monetizationData.js",
  "./src/data/parties.js",
  "./src/data/populationData.js",
  "./src/data/progressionData.js",
  "./src/data/releaseData.js",
  "./src/data/securityData.js",
  "./src/data/tutorialData.js",
  "./src/data/worldDiplomacyData.js",
  "./src/game.js",
  "./src/i18n/locales/en.js",
  "./src/i18n/locales/es.js",
  "./src/i18n/locales/pt-BR.js",
  "./src/styles.css",
  "./src/systems/budgetTax.js",
  "./src/systems/cabinetAdministration.js",
  "./src/systems/calculations.js",
  "./src/systems/coreLoop.js",
  "./src/systems/crisis.js",
  "./src/systems/diplomacy.js",
  "./src/systems/economy.js",
  "./src/systems/economyDeep.js",
  "./src/systems/elections.js",
  "./src/systems/events.js",
  "./src/systems/government.js",
  "./src/systems/governmentCreation.js",
  "./src/systems/governmentInstitutions.js",
  "./src/systems/media.js",
  "./src/systems/monetization.js",
  "./src/systems/population.js",
  "./src/systems/progression.js",
  "./src/systems/security.js",
  "./src/systems/worldDiplomacy.js",
  "./src/ui/audio.js",
  "./src/ui/feedback.js",
  "./src/ui/render.js",
  "./src/ui/tutorial.js"
];

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    const results = await Promise.allSettled(PRECACHE_URLS.map(async url => {
      const response = await fetch(url, { cache: "reload" });
      if (!response || !response.ok) throw new Error(`precache ${url}: ${response?.status || "network"}`);
      await cache.put(url, response.clone());
    }));
    const shell = await cache.match("./index.html", { ignoreSearch: true });
    if (!shell) throw new Error("DIPLOCRAFT critical shell unavailable");
    const optionalFailures = results.filter(item => item.status === "rejected").length;
    if (optionalFailures) console.warn(`[DIPLOCRAFT] ${optionalFailures} optional precache files unavailable; source fallbacks remain active.`);
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME).map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    if (response && response.ok) await cache.put(request, response.clone());
    return response;
  } catch (_) {
    return (await cache.match(request, {ignoreSearch:true})) || (await cache.match("./index.html")) || Response.error();
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && response.ok) { const cache = await caches.open(CACHE_NAME); await cache.put(request,response.clone()); }
  return response;
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  const network = fetch(request).then(response => { if (response && response.ok) cache.put(request,response.clone()); return response; }).catch(() => null);
  return cached || (await network) || Response.error();
}

self.addEventListener("fetch", event => {
  const request=event.request;
  if (request.method !== "GET") return;
  const url=new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === "navigate") { event.respondWith(networkFirst(request)); return; }
  if (url.pathname.includes("/assets/runtime/") || url.pathname.includes("/assets/pwa/")) { event.respondWith(staleWhileRevalidate(request)); return; }
  event.respondWith(cacheFirst(request));
});

self.addEventListener("message", event => {
  const type=event.data && event.data.type;
  if (type === "SKIP_WAITING") self.skipWaiting();
  if (type === "GET_VERSION" && event.ports && event.ports[0]) event.ports[0].postMessage({version:VERSION,cache:CACHE_NAME});
});
