// AUTO-GENERATED by tools/generate_build.py from build.config.json. DO NOT EDIT.
export const BUILD = Object.freeze({
  "project": "DIPLOCRAFT",
  "productName": "DIPLOCRAFT — Simulador Político e Geopolítico",
  "version": "2.0.0",
  "stageNumber": 29,
  "stageName": "GOLD V2 INTERNACIONAL",
  "stage": "Fase 29 — GOLD V2 INTERNACIONAL",
  "stageShort": "Fase 29 • GOLD V2 INTERNACIONAL",
  "date": "19/06/2026",
  "dateISO": "2026-06-19",
  "time": "18:54",
  "timezone": "America/Sao_Paulo",
  "stamp": "20260619_1854",
  "status": "GOLD_V2_INTERNATIONAL_VERIFIED",
  "artifact": "DIPLOCRAFT_v2.0.0_FASE-29_GOLD-V2-INTERNACIONAL_build_20260619_1854.zip",
  "source": "build.config.json",
  "sourceSHA256": "59de07af832167c50b4f3fadb1be3827a7033754efb7041d930498a3ee71923f",
  "saveSchema": 3,
  "saveKey": "diplocraft_save_v101",
  "defaultLocale": "pt-BR",
  "supportedLocales": [
    "pt-BR",
    "en",
    "es"
  ],
  "i18n": {
    "enabled": true,
    "default_locale": "pt-BR",
    "supported_locales": [
      "pt-BR",
      "en",
      "es"
    ],
    "storage_key": "diplocraft_locale_v1",
    "hot_switch": true,
    "save_independent": true,
    "intl_formatting": true,
    "dom_translation": true,
    "legacy_fallback": false,
    "catalog_generator": "tools/generate_i18n.py",
    "catalog_source": "tools/i18n_seed.json",
    "audit": "tests/run_i18n_audit.py",
    "editorial_complete": true,
    "exact_content_translation": true,
    "missing_translation_registry": true,
    "catalog_key_minimum": 1300,
    "localization_audit": "tests/run_localization_complete_audit.py"
  },
  "scrollTouchRecovery": {
    "enabled": true,
    "scroll_screens": [
      "menu",
      "create"
    ],
    "desktop_wheel": true,
    "touch_pan_y": true,
    "keyboard_page_navigation": true,
    "scroll_assist": true,
    "scrollbar_gutter": "stable",
    "audit": "tests/run_scroll_touch_audit.py"
  },
  "saveArchitecture": {
    "enabled": true,
    "registry_schema": 1,
    "save_schema": 3,
    "max_profiles": 4,
    "slots_per_profile": 3,
    "snapshots_per_slot": 3,
    "manual_backups_per_slot": 5,
    "transactional_writes": true,
    "legacy_migration": true,
    "export_import_checksum": true,
    "history_limit": 60,
    "manager_ui": true,
    "mobile_audited": true,
    "audit": "tests/run_save_architecture_audit.py"
  },
  "coreLoop2": {
    "enabled": true,
    "schema": 2,
    "term_days": 1460,
    "maximum_terms": 2,
    "weekly_action_points": true,
    "delayed_consequences": true,
    "quarterly_reviews": true,
    "annual_reports": true,
    "automatic_stabilizers": true,
    "real_career_outcomes": true,
    "idle_collapse_blocking": true,
    "audit": "tests/run_core_loop_2_audit.py"
  },
  "governmentCreation": {
    "enabled": true,
    "schema": 1,
    "playable_countries": 1,
    "political_systems": 3,
    "leader_ideologies": 5,
    "difficulty_levels": 4,
    "starting_scenarios": 4,
    "strategic_objectives": 5,
    "party_logo_cards": 12,
    "audit": "tests/run_government_creation_audit.py"
  },
  "summary": "Gold v2.0 Internacional com localização reforçada, mercados globais, compliance multirregional, suporte, loja, comunidade, telemetria segura e operação global integrada ao Gold Master, Alpha/Beta, PWA, saves, mobile e Core Loop 2.0."
});

export const BUILD_LABEL = "DIPLOCRAFT v2.0.0 • 19/06/2026 18:54 • Fase 29 • GOLD V2 INTERNACIONAL";
