#!/usr/bin/env python3
from pathlib import Path
import argparse, json, hashlib
ROOT=Path(__file__).resolve().parents[1]
SEED=ROOT/'tools/i18n_seed.json'
OUT=ROOT/'src/i18n/locales'
META=ROOT/'meta/i18n.json'

def dump(data): return json.dumps(data, ensure_ascii=False, indent=2)+'\n'

def generated_files(seed):
    locales=seed['locales']; entries=seed['entries']
    keys=sorted(entries)
    errors=[]
    for key in keys:
        record=entries[key]
        for loc in locales:
            value=record.get(loc)
            if not isinstance(value,str) or not value.strip(): errors.append(f'{key}:{loc}')
    if errors: raise ValueError('Missing translations: '+', '.join(errors))
    files={}
    for loc in locales:
        messages={key:entries[key][loc] for key in keys}
        content='// AUTO-GENERATED by tools/generate_i18n.py. DO NOT EDIT.\n'
        content+=f'export const LOCALE = {json.dumps(loc)};\n'
        content+=f'export const MESSAGES = Object.freeze({json.dumps(messages,ensure_ascii=False,indent=2)});\n'
        files[f'src/i18n/locales/{loc}.js']=content
    source_hash=hashlib.sha256(SEED.read_bytes()).hexdigest()
    meta={
      'generated_by':'tools/generate_i18n.py','source':'tools/i18n_seed.json','source_sha256':source_hash,
      'default_locale':seed['default_locale'],'supported_locales':locales,'key_count':len(keys),
      'keys':keys,'status':'I18N_CORE_GENERATED'
    }
    files['meta/i18n.json']=dump(meta)
    return files, {'locales':locales,'keys':len(keys),'source_sha256':source_hash}

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    seed=json.loads(SEED.read_text(encoding='utf-8'))
    files, summary=generated_files(seed)
    drift=[]
    for rel,content in files.items():
        path=ROOT/rel
        if args.check:
            current=path.read_text(encoding='utf-8') if path.exists() else None
            if current!=content: drift.append(rel)
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(content,encoding='utf-8')
    if drift:
        print('I18N DRIFT: '+', '.join(drift))
        return 1
    print(json.dumps(summary,ensure_ascii=False,indent=2))
    return 0

if __name__=='__main__': raise SystemExit(main())
