const screens=[...document.querySelectorAll('.screen')];
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));document.body.scrollTop=0;document.documentElement.scrollTop=0;}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(!go)return;const sys=go.dataset.system;if(sys){openSystem(sys)}show(go.dataset.go)});
const avatarFiles=['char_leader_male_white_v1.png','char_leader_male_black_v1.png','char_leader_male_elder_v1.png','char_leader_male_elder_refined_v1.png','char_leader_latest_v1.png'];
const avatars=document.getElementById('avatars');if(avatars){avatarFiles.forEach((f,i)=>{let b=document.createElement('button');b.className='avatar'+(i===0?' active':'');b.innerHTML=`<img src="assets/characters/${f}">`;b.onclick=()=>{document.querySelectorAll('.avatar').forEach(a=>a.classList.remove('active'));b.classList.add('active');document.querySelector('.portrait img').src=`assets/characters/${f}`};avatars.appendChild(b)})}
document.getElementById('leaderName')?.addEventListener('input',e=>{document.getElementById('hudName').textContent=e.target.value.toUpperCase()||'ALEXANDER MORGAN'});
const systems={economy:['ECONOMIA','Gerencie sua economia, comércio e recursos.','bg_economy_financial_center_v1.png','+2,45%','Crescimento em 7 dias'],diplomacy:['DIPLOMACIA','Negocie acordos, sanções e blocos internacionais.','bg_diplomacy_room_v1.png','85/100','Reputação global'],military:['MILITAR','Treine forças e desenvolva estratégias de defesa.','bg_military_command_center_v1.png','92%','Prontidão'],government:['GOVERNO','Aprove leis e melhore instituições nacionais.','bg_parliament_v1.png','78%','Popularidade'],intelligence:['INTELIGÊNCIA','Colete informações e realize operações secretas.','bg_global_map_v1.png','78/100','Nível de inteligência'],projects:['PROJETOS','Construa obras e fortaleça infraestrutura.','bg_dashboard_city_view_v1.png','68%','Projeto em andamento'],crisis:['CRISES','Gerencie crises globais e decisões de alto risco.','bg_crisis_scene_v1.png','ALTO','Nível de ameaça'],technology:['PESQUISA & TECNOLOGIA','Invista em inovação e desbloqueie avanços.','bg_global_map_v1.png','42%','Pesquisa atual']};
function openSystem(key){let s=systems[key]||systems.economy;document.getElementById('systemTitle').textContent=s[0];document.getElementById('systemSub').textContent=s[1];const card=document.getElementById('systemCard');card.style.backgroundImage=`linear-gradient(90deg,rgba(0,0,0,.78),rgba(0,0,0,.25)),url('assets/backgrounds/${s[2]}')`;card.innerHTML=`<h3>${s[0]}</h3><p>${s[1]}</p><div class="big">${s[3]}</div><p>${s[4]}</p><div class="bar green"><i style="width:72%"></i></div>`;}
openSystem('economy');show('menu');
